const ShopActionType = {
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCEESS: 'FETCH_COLLECTIONS_SUCCEESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
}

export default ShopActionType;